Адаптивные декоративные элементы
htmlacademy-adaptive/378519-pognali-21 pull request #10
Opened 2020-12-23 10:33 UTC by garmonica

По пиксель перфекту более менее подгоняла, единственное, на странице Каталога в фильтре на десктопной версии достаточно сильно не совпадает список стран, как ни крути. Там в самом макете разные отступы у блоков и по вертикали и по горизонтали. Можешь что-то посоветовать? Просто отдельным блокам задавать другой отступ? 

А ещё длинное тире как сделать, обернуть в span и задать другой шрифт? 
https://ibb.co/9V9Qd3J

2020-12-23 10:42 UTC, garmonica commented on source/index.html
>          <ul class="intro__list">
Разваливается на десктопе. Надо будет переделать похоже.

2020-12-24 18:54 UTC, ElseeCCD requested changes
Нужно подправить подключение normalize и добавить контейнеры для контента

2020-12-24 18:54 UTC, ElseeCCD commented on source/less/blocks/intro.less
> +.intro__item:nth-child(4n-3) {
если первый, почему не просто `nth-child(1)`?

2020-12-24 18:54 UTC, ElseeCCD commented on source/less/blocks/intro.less
> +.intro__item:nth-child(4n-2) {
тот же самый вопрос )

2020-12-24 18:54 UTC, ElseeCCD commented on source/less/blocks/intro.less
> +.intro__item:nth-child(4n) {
т.е. это на случай, если добавятся еще элементы?
Тут какая-то вообще очень сложная верстка, и even и nth-child(4n). Оно точно всё надо?

2020-12-24 18:54 UTC, ElseeCCD commented on source/less/blocks/intro.less
> +.intro__item:not(:nth-child(4n-3)) {
если всё-таки передумаешь добавлять n, то тут можно будет переписать как `.intro__item+.intro__item`

2020-12-26 19:42 UTC, merged