Разметка главной страницы
htmlacademy-adaptive/378519-pognali-21 pull request #2
Opened 2020-11-18 12:44 UTC by garmonica

2020-11-18 16:51 UTC, ElseeCCD requested changes

2020-11-18 16:51 UTC, ElseeCCD commented on source/index.html
> +          <li class="intro_item">Путешествуйте вместе!</li>
одно нижнее подчеркивание потерялось во всех элементах `intro_item`, нужно `intro__item`

2020-11-18 16:51 UTC, ElseeCCD commented on source/index.html
> +      <section class="profile-add">
Что тут подразумевалось под add? "Добавить"?

2020-11-19 08:42 UTC, garmonica commented on source/index.html
> +          <li class="intro_item">Путешествуйте вместе!</li>
Точно, опечатка, исправлю

2020-11-19 08:49 UTC, garmonica commented on source/index.html
> +      <section class="profile-add">
В этом разделе я не совсем разобралась. https://ibb.co/CsSdJn5
Текст, похожий на заголовок "Добавьте свой профиль", соответственно, назвала класс "profile-add," хотя ниже идут тарифы.

2020-11-19 09:10 UTC, merged